apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    {{ include "helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels: 
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      initContainers:
      - name: wait-for-redis
        image: busybox:1.37
        command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-redis 6379; do echo "Waiting for Redis..."; sleep 2; done; echo "Redis ready"']
      - name: wait-for-mysql
        image: busybox:1.37
        command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-mysql 3306; do echo "Waiting for MySQL..."; sleep 2; done; echo "MySQL ready"']
      containers:
      - name: {{ .Release.Name }}-backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.ports.port }}
        env:
        - name: MYSQL_USER
          value: "{{ .Values.env.MYSQL_USER }}"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_HOST
          value: "{{ .Release.Name }}-mysql"
        - name: MYSQL_PORT
          value: "{{ .Values.env.MYSQL_PORT }}"
        - name: MYSQL_DB
          value: "{{ .Values.env.MYSQL_DATABASE }}"
        - name: REDIS_HOST
          value: "{{ .Release.Name }}-redis"
        - name: REDIS_PORT
          value: "{{ .Values.env.REDIS_PORT }}"
        - name: FE_HOST
          value: "{{ .Release.Name }}-frontend"
        resources:
          {{ toYaml .Values.backend.resources | nindent 10 }}
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
