apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    {{ include "helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels: 
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
      - name: {{ .Release.Name }}-mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mysql.service.ports.port }}
        env:
        - name: MYSQL_USER
          value: "{{ .Values.env.MYSQL_USER }}"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_HOST
          value: "{{ .Release.Name }}-mysql"
        - name: MYSQL_PORT
          value: "{{ .Values.env.MYSQL_PORT }}"
        - name: MYSQL_DATABASE
          value: "{{ .Values.env.MYSQL_DATABASE }}"
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 20
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 20
          failureThreshold: 5
        volumeMounts:
          {{ toYaml .Values.mysql.volumeMounts | nindent 10 }}
      volumes:
      - name: {{ .Values.mysql.volumes.name }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mysql-pvc
